# The public documentation URL, used for sitemap.xml
url: "http://testdocs.telerik.com/windows-universal"

# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock]
navigation:
## List your directory names and order here, like this:
    installation-and-deployment:
        title: "Installation and Deployment"
        position: 2
    common:
        title: "Common"
        position: 3
    common/localization:
        title: "Localization"
        position: 3
    common/troubleshooting:
        title: "Troubleshooting"
        position: 4
    controls:
        title: "Controls"
        position: 4
    controls/radautocompletebox:
        title: "RadAutocompletebox"
        position: 4
    controls/radbulletgraph:
        title: "RadBulletgraph"
        position: 4
    controls/radbusyindicator:
        title: "RadBusyindicator"
        position: 4
    controls/radcalendar:
        title: "RadCalendar"
        position: 4
    controls/radchart:
        title: "RadChart"
        position: 4
    controls/raddataboundlistbox:
        title: "RadDataboundListbox"
        position: 4
    controls/raddatagrid:
        title: "RadDataGrid"
        position: 4
    controls/raddatepicker-and-radtimepicker:
        title: "RadDatepicker and RadTimepicker"
        position: 4
    controls/radgauge:
        title: "RadGauge"
        position: 4
    controls/radhubtile:
        title: "RadHubtile"
        position: 4
    controls/radmap:
        title: "RadMap"
        position: 4
    controls/radnumericbox:
        title: "RadNumericBox"
        position: 4
    controls/radpagination:
        title: "RadPagination"
        position: 4
    controls/radradialmenu:
        title: "RadRadialMenu"
        position: 4
    controls/radrangeslider:
        title: "RadRangeSlider"
        position: 4
    controls/radrating:
        title: "RadRating"
        position: 4		
    data-storage:
        title: "Data Storage"
        position: 5
    telerik-examples:
        title: "Telerik Examples"
        position: 6

## The application virtual path
baseurl: /windows-universal

## The product name
productName: "Telerik UI for Windows Universal"

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:eblhnfskwrk'

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM

